USE [master]
GO

/****** Object:  Table [dbo].[Tareas]    Script Date: 23/04/2024 23:55:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tareas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Finalizada] [bit] NOT NULL,
	[Orden] [int] NOT NULL,
 CONSTRAINT [PK_Tareas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Tareas] ADD  CONSTRAINT [DF_Tareas_Orden]  DEFAULT ((0)) FOR [Orden]
GO


INSERT INTO TAREAS VALUES ('TAREA A', 0, 1)
INSERT INTO TAREAS VALUES ('TAREA B', 0, 2)
INSERT INTO TAREAS VALUES ('TAREA C', 0, 3)
INSERT INTO TAREAS VALUES ('TAREA D', 0, 4)

